- hosts: my-deployment-server
  tasks:
    - name: Pull Docker image
      docker_image:
        name: prathvirajbn/calcapp:latest
        source: pull
    - name: Create Docker container
      docker_container:
        name: calc-app
        image: prathvirajbn/calcapp:latest
          - "80:80"
    - name: Start Docker container
      docker_container:
        name: calc-app
        state: started
